//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string productid { get; set; }
        public string productname { get; set; }
        public System.DateTime productcreatedon { get; set; }
        public System.DateTime productmodifedon { get; set; }
    }
}
