//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public string registeruser_id { get; set; }
        public string registeruser_username { get; set; }
        public string registeruser_email { get; set; }
        public string registeruser_password { get; set; }
        public System.DateTime registeruser_createdon { get; set; }
        public System.DateTime registeruser_modifiedon { get; set; }
        public byte registeruser_rowstate { get; set; }
    }
}
